#!/bin/bash
set -e

# CCG GitHub Action Entrypoint
# Arguments: threshold, include, exclude, strategy, fail-on-issues, comment-on-pr, max-hotspots, guard-rules

THRESHOLD="${1:-70}"
INCLUDE="${2:-**/*.ts,**/*.tsx,**/*.js,**/*.jsx}"
EXCLUDE="${3:-node_modules/**,dist/**,build/**,.git/**}"
STRATEGY="${4:-mixed}"
FAIL_ON_ISSUES="${5:-true}"
COMMENT_ON_PR="${6:-true}"
MAX_HOTSPOTS="${7:-20}"
GUARD_RULES="${8:-all}"

echo "=========================================="
echo "  Claude Code Guardian - Code Analysis"
echo "=========================================="
echo ""
echo "Configuration:"
echo "  Threshold:     $THRESHOLD"
echo "  Strategy:      $STRATEGY"
echo "  Max Hotspots:  $MAX_HOTSPOTS"
echo "  Fail on Issues: $FAIL_ON_ISSUES"
echo ""

# Navigate to workspace
cd "$GITHUB_WORKSPACE" || { echo "Error: Cannot access workspace"; exit 1; }

# Create output directory
OUTPUT_DIR=".ccg-output"
mkdir -p "$OUTPUT_DIR"

# Initialize results
HOTSPOTS_COUNT=0
AVG_COMPLEXITY=0
MAX_COMPLEXITY=0
TOTAL_ISSUES=0
FILES_ANALYZED=0
PASSED="true"

# Run CCG quick analysis
echo "Running code analysis..."
echo ""

# Run CCG code-scan and capture output
CCG_SCAN_OUTPUT=$(ccg code-scan --json 2>/dev/null || echo '{"error": true}')

# Check if scan was successful
if echo "$CCG_SCAN_OUTPUT" | jq -e '.error' > /dev/null 2>&1; then
    echo "Warning: CCG scan encountered an error, using fallback analysis"

    # Fallback: Count files manually
    FILES_ANALYZED=$(find . -type f \( -name "*.ts" -o -name "*.tsx" -o -name "*.js" -o -name "*.jsx" \) \
        ! -path "*/node_modules/*" ! -path "*/dist/*" ! -path "*/.git/*" | wc -l)
else
    # Parse scan results
    FILES_ANALYZED=$(echo "$CCG_SCAN_OUTPUT" | jq -r '.totalFiles // 0')
fi

echo "Files analyzed: $FILES_ANALYZED"

# Run CCG code-optimize for hotspot detection
echo ""
echo "Detecting hotspots..."
CCG_HOTSPOTS_OUTPUT=$(ccg code-optimize --strategy "$STRATEGY" --max-hotspots "$MAX_HOTSPOTS" --json 2>/dev/null || echo '{"hotspots": []}')

# Parse hotspots
if command -v jq &> /dev/null; then
    HOTSPOTS_COUNT=$(echo "$CCG_HOTSPOTS_OUTPUT" | jq -r '.hotspots | length // 0')
    AVG_COMPLEXITY=$(echo "$CCG_HOTSPOTS_OUTPUT" | jq -r '.avgComplexity // 0')
    MAX_COMPLEXITY=$(echo "$CCG_HOTSPOTS_OUTPUT" | jq -r '.maxComplexity // 0')
fi

echo "Hotspots found: $HOTSPOTS_COUNT"
echo "Average complexity: $AVG_COMPLEXITY"
echo "Maximum complexity: $MAX_COMPLEXITY"

# Run CCG guard validation on changed files (if in PR context)
if [ -n "$GITHUB_EVENT_PATH" ] && [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
    echo ""
    echo "Running guard validation on PR changes..."

    # Get changed files from PR
    CHANGED_FILES=$(git diff --name-only origin/$GITHUB_BASE_REF...HEAD 2>/dev/null | grep -E '\.(ts|tsx|js|jsx)$' || echo "")

    if [ -n "$CHANGED_FILES" ]; then
        for file in $CHANGED_FILES; do
            if [ -f "$file" ]; then
                GUARD_OUTPUT=$(ccg guard "$file" --json 2>/dev/null || echo '{"issues": 0}')
                FILE_ISSUES=$(echo "$GUARD_OUTPUT" | jq -r '.issues // 0')
                TOTAL_ISSUES=$((TOTAL_ISSUES + FILE_ISSUES))
            fi
        done
        echo "Total guard issues: $TOTAL_ISSUES"
    fi
else
    echo ""
    echo "Not in PR context, skipping guard validation on changed files"
fi

# Check thresholds
echo ""
echo "Checking thresholds..."

if [ "$MAX_COMPLEXITY" -gt "$THRESHOLD" ]; then
    echo "FAIL: Maximum complexity ($MAX_COMPLEXITY) exceeds threshold ($THRESHOLD)"
    PASSED="false"
fi

if [ "$FAIL_ON_ISSUES" = "true" ] && [ "$TOTAL_ISSUES" -gt 0 ]; then
    echo "FAIL: Found $TOTAL_ISSUES guard issues"
    PASSED="false"
fi

# Generate report
REPORT_PATH="$OUTPUT_DIR/ccg-report.md"
echo ""
echo "Generating report: $REPORT_PATH"

cat > "$REPORT_PATH" << EOF
# CCG Code Analysis Report

## Summary

| Metric | Value | Status |
|--------|-------|--------|
| Files Analyzed | $FILES_ANALYZED | - |
| Hotspots Found | $HOTSPOTS_COUNT | $([ "$HOTSPOTS_COUNT" -gt 10 ] && echo "Warning" || echo "OK") |
| Avg Complexity | $AVG_COMPLEXITY | $([ "$AVG_COMPLEXITY" -gt 50 ] && echo "Warning" || echo "OK") |
| Max Complexity | $MAX_COMPLEXITY | $([ "$MAX_COMPLEXITY" -gt "$THRESHOLD" ] && echo "FAIL" || echo "OK") |
| Guard Issues | $TOTAL_ISSUES | $([ "$TOTAL_ISSUES" -gt 0 ] && echo "Warning" || echo "OK") |

## Configuration

- **Threshold**: $THRESHOLD
- **Strategy**: $STRATEGY
- **Max Hotspots**: $MAX_HOTSPOTS

## Result

**Status**: $([ "$PASSED" = "true" ] && echo "PASSED" || echo "FAILED")

---
*Generated by [Claude Code Guardian](https://github.com/codeguardian/claude-code-guardian)*
EOF

# Comment on PR if enabled
if [ "$COMMENT_ON_PR" = "true" ] && [ -n "$GITHUB_TOKEN" ] && [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
    echo ""
    echo "Posting comment to PR..."

    COMMENT_BODY=$(cat "$REPORT_PATH" | jq -Rs .)
    PR_NUMBER=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")

    curl -s -X POST \
        -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments" \
        -d "{\"body\": $COMMENT_BODY}" > /dev/null

    echo "Comment posted successfully"
fi

# Set outputs for GitHub Actions
echo "hotspots-count=$HOTSPOTS_COUNT" >> "$GITHUB_OUTPUT"
echo "avg-complexity=$AVG_COMPLEXITY" >> "$GITHUB_OUTPUT"
echo "max-complexity=$MAX_COMPLEXITY" >> "$GITHUB_OUTPUT"
echo "total-issues=$TOTAL_ISSUES" >> "$GITHUB_OUTPUT"
echo "files-analyzed=$FILES_ANALYZED" >> "$GITHUB_OUTPUT"
echo "report-path=$REPORT_PATH" >> "$GITHUB_OUTPUT"
echo "passed=$PASSED" >> "$GITHUB_OUTPUT"

# Final status
echo ""
echo "=========================================="
if [ "$PASSED" = "true" ]; then
    echo "  Analysis PASSED"
    echo "=========================================="
    exit 0
else
    echo "  Analysis FAILED"
    echo "=========================================="
    exit 1
fi
